version: "3.9"
services:
  api_service:
    image: smls-server:latest
    command: start
    networks:
      - smls
    ports:
      - "4000:4000"
  model_runner:
    image: smls-model-runner:latest
    restart: always
    networks:
      - smls
    deploy:
      mode: replicated
      replicas: 2
  postgres:
    image: postgres:13
    restart: always
    networks:
      - smls
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  rabbitmq:
    image: rabbitmq:3-management
    networks:
      - smls
volumes:
  pg-volume:

networks:
  smls: 